schema_version: 1

context:
  name: anneal
  version: "0.7.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/anneal/anneal-${{ version }}.tar.gz
  sha256: 09e13c0eda230712202a28ffc10dc3cb00dcedd3c2d8852bbc86a92124acbb7f

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin
    - array-api-compat
    - numpy
  run:
    - python
    - numpy
    - array-api-compat

tests:
  - python:
      imports:
        - anneal
      pip_check: true

about:
  homepage: https://github.com/HaoZeke/anneal
  summary: Simulated annealing and quenching for Python
  license: MIT
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  repository: https://github.com/HaoZeke/anneal

extra:
  recipe-maintainers:
    - HaoZeke
